### ISSUE TITLE
Possible values for allowedOrigins are not listed properly in the readme.

### ISSUE THREAD

**Issue by jrrios** [IBM-Swift/Kitura-CORS#28]
It took me a while to realize that the possible values were the bullet points under the "allowedOrigins" in the readme. Not really a big issue, it can be understood after re-reading it a couple of times but just wanted to point it out.

-thanks

**Comment by irar2** [comment]
@jrriosBC Thanks for pointing this out. I fixed the indentation, is it OK now?

**Comment by jrrios** [comment]
Looks great. Thanks!
